### PR TITLE
Unit Tests & Basic Refactor and a bunch of missing endpoints

### PR DESCRIPTION
**Pull request by Alex-451**
"Useful" unit tests.

### CODE REVIEW

**Review by li223 — CHANGES_REQUESTED** [review]
Cool, but this repo isn't big enough for a logo yet.

Requires removal.

**Review by li223 — CHANGES_REQUESTED** [review]
See previous

**Review by li223 — APPROVED** [review]

**Comment by li223** [comment]
i give up.

**Comment by Alex-451** [comment]
hahaha that was great 😂

**Comment by li223** [comment]
Apologies for the spam. Some reason had this idea in my head that it reviewed individual files instead of the entire PR

**Pull request merged**
